### ISSUE TITLE
Issue with 512GB SSD NVME Lenovo AM6671

### ISSUE THREAD

**Issue by votruongvu** [kaneve/clover-x1c5#1]
Thanks for your sharing the config. But I have an issue that comes to Disk Utility cannot find my SSD (512GB SSD NVME Lenovo AM6671). Do you have any idea to resolve this ?

**Comment by kaneve** [comment]
try the patches in this config , hope it helps. 
https://github.com/RehabMan/patch-nvme/blob/master/config_patches.plist

**Comment by votruongvu** [comment]
Thanks for your awesome reply...It works...but I have another problem that MacOS need network to install ("The recovery server could not be contacted")..I cannot use your suggest card wifi ...it's not sell in my country so I use the TPLink usb wifi...and extract the kext into EFI. It can recoginze my usb wifi in Network Utility ...but I do not know how to set up to connect wifi host..as wifi aiport does not show in installation screen,

**Comment by kaneve** [comment]
It seems you are trying to perform an upgrade install of MacOS...? 
If you have a MacOS alreadly installed, you need a TPLink app to set wifi connection .
If you are in recovery mode, maybe command 'networksetup' can help you to set wifi, but im not sure.
I suggest download the dmg installation package and writing it to the U disk ,then boot clover(UEFI) and select U disk ,then you can finish installation without network connection.

**Comment by votruongvu** [comment]
I used the USB Erthernet with the driver that they provided to pass the checking internet. Installing successfully. Thanks for your support. you are my hero :)
