### ISSUE TITLE
hdmi 接入后，内屏直接黑了

### ISSUE THREAD

**Issue by sullevy** [kaneve/clover-x1c5#2]
如题

**Comment by kaneve** [comment]
手头没设备，我回头测试一下。你可以先试试这个帖子说的方法：
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1780428&highlight=hdmi

**Comment by kaneve** [comment]
测试了dell 2k显示器和LG 4k电视，插上HDMI双屏均正常显示。建议你试试改下刷新频率、分辨率等，试试其他显示器。

**Comment by sullevy** [comment]
感谢，我自己有次发现盖子合上再重新打开就好了，然后看到帖子也说这个问题，可能还是刷新率的事。感谢！也非常感谢你的这份文件，省了不少事情。
